### ISSUE TITLE
Infografia de los Sistemas Numericos 

### ISSUE THREAD

**Issue by Berenice1719** [SistemasTecTlaxiaco/infografia-Berenice1719#1]
[Infografia.pdf](https://github.com/user-attachments/files/16734838/Infografia.pdf)

**Comment by AlynGomez12** [comment]
Redacción y Ortografía:13/14
Exposición de ideas Centrales:16/16
Organización de ideas centrales:14/14
Uso de Imágenes y Colores:13/14
Presentación Visual:13/14
Referencias:14/14
Presentación:14/14
Calificación Final: 19.2/20
Agregar nombre y grupo.

**Comment by josealfredo79** [comment]
Bien hecho y revisado..
